package pg

import (
	"context"
	"fmt"
	"testing"
)

// These tests require a live PostgreSQL server, see getTestConnString (db_example_test.go) and
// the PG_CONNSTRING environment variable. Run with, e.g.:
//
//	PG_CONNSTRING="..." go test -run 'TestRepositoryInsertOnConflict|TestRepositoryInsertSingleOnConflictDoNothing|TestUpdateOrInsert' -v .

// conflictScratchItem is a scratch entity registered only for this file's tests, mirroring
// paginationItem's pattern (pagination_live_test.go): its scratch table is created/dropped with
// plain DDL, carrying a UNIQUE (a,b) constraint so InsertOnConflict/InsertSingleOnConflict/
// UpdateOrInsert have a real conflict target to exercise.
type conflictScratchItem struct {
	// identity (not just primary) marks ID AutoGenerated, so extractArguments/BuildBulkInsertQuery
	// always omit it from the INSERT column list, unlike a bare "primary" bigint/int PK, which
	// (having no "default" tag to pair with the isZero skip, unlike, say, a UUID PK, which gets
	// one implicitly) would otherwise be written as an explicit literal 0, colliding with
	// PostgreSQL's own BIGSERIAL-assigned id the moment more than one row exists.
	ID int64  `pg:"type=bigint,primary,identity"`
	A  string `pg:"type=varchar(255)"`
	B  string `pg:"type=varchar(255)"`
	C  string `pg:"type=varchar(255)"`
}

const conflictScratchTable = "conflict_scratch_items"

// openConflictTestConnection opens a *DB whose schema has only conflictScratchItem registered, so
// NewRepository[conflictScratchItem] can resolve its table descriptor. It does not create the
// table itself (see setupConflictScratchTable) or run CreateSchema/DeleteSchema.
func openConflictTestConnection() (*DB, error) {
	schema := NewSchema()
	schema.MustRegister(conflictScratchTable, conflictScratchItem{})

	return Open(context.Background(), schema, getTestConnString())
}

// setupConflictScratchTable (re)creates conflictScratchTable with plain DDL, including the
// UNIQUE (a,b) constraint InsertOnConflict/InsertSingleOnConflict/UpdateOrInsert target in these
// tests.
func setupConflictScratchTable(ctx context.Context, db *DB) error {
	if _, err := db.Exec(ctx, "DROP TABLE IF EXISTS "+conflictScratchTable); err != nil {
		return err
	}

	_, err := db.Exec(ctx, fmt.Sprintf(
		`CREATE TABLE %s (
			id BIGSERIAL PRIMARY KEY,
			a VARCHAR(255) NOT NULL,
			b VARCHAR(255) NOT NULL,
			c VARCHAR(255) NOT NULL,
			UNIQUE (a, b)
		)`, conflictScratchTable))
	return err
}

// TestRepositoryInsertOnConflict verifies InsertOnConflict's Columns+SetColumns partial update:
// inserting a second row with the same (a,b) but a different c updates only c, leaving a and b
// untouched, and does not insert a second row.
func TestRepositoryInsertOnConflict(t *testing.T) {
	db, err := openConflictTestConnection()
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	ctx := context.Background()
	if err = setupConflictScratchTable(ctx, db); err != nil {
		t.Fatal(err)
	}
	defer db.Exec(ctx, "DROP TABLE IF EXISTS "+conflictScratchTable)

	repo := NewRepository[conflictScratchItem](db)
	oc := OnConflict{Columns: []string{"a", "b"}, SetColumns: []string{"c"}}

	if err := repo.InsertOnConflict(ctx, oc, conflictScratchItem{A: "x", B: "y", C: "first"}); err != nil {
		t.Fatalf("InsertOnConflict (first insert): %v", err)
	}
	if err := repo.InsertOnConflict(ctx, oc, conflictScratchItem{A: "x", B: "y", C: "second"}); err != nil {
		t.Fatalf("InsertOnConflict (conflicting insert): %v", err)
	}

	count, err := repo.Count(ctx, "SELECT COUNT(*) FROM "+conflictScratchTable+" WHERE a = 'x' AND b = 'y'")
	if err != nil {
		t.Fatalf("Count: %v", err)
	}
	if count != 1 {
		t.Fatalf("expected exactly 1 row for (a,b)=('x','y') after the conflicting insert, got %d", count)
	}

	items, err := repo.Select(ctx, "SELECT * FROM "+conflictScratchTable+" WHERE a = 'x' AND b = 'y'")
	if err != nil {
		t.Fatalf("Select: %v", err)
	}
	if len(items) != 1 {
		t.Fatalf("expected 1 row, got %d", len(items))
	}
	if got := items[0]; got.A != "x" || got.B != "y" || got.C != "second" {
		t.Fatalf("expected {A:x B:y C:second} after the partial SetColumns update, got %+v", got)
	}
}

// TestRepositoryInsertSingleOnConflictDoNothing verifies InsertSingleOnConflict's DoNothing +
// idPtr semantics: the first insert returns the new row's id, and a duplicate insert (same
// (a,b), DoNothing) returns ErrNoRows instead of a stale/zero idPtr.
func TestRepositoryInsertSingleOnConflictDoNothing(t *testing.T) {
	db, err := openConflictTestConnection()
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	ctx := context.Background()
	if err = setupConflictScratchTable(ctx, db); err != nil {
		t.Fatal(err)
	}
	defer db.Exec(ctx, "DROP TABLE IF EXISTS "+conflictScratchTable)

	repo := NewRepository[conflictScratchItem](db)
	oc := OnConflict{Columns: []string{"a", "b"}, DoNothing: true}

	var firstID int64
	if err := repo.InsertSingleOnConflict(ctx, oc, conflictScratchItem{A: "p", B: "q", C: "v1"}, &firstID); err != nil {
		t.Fatalf("InsertSingleOnConflict (first insert): %v", err)
	}
	if firstID == 0 {
		t.Fatal("expected a non-zero id from the first insert")
	}

	var secondID int64
	err = repo.InsertSingleOnConflict(ctx, oc, conflictScratchItem{A: "p", B: "q", C: "v2"}, &secondID)
	if !IsErrNoRows(err) {
		t.Fatalf("expected ErrNoRows for a DO NOTHING-skipped duplicate insert, got: %v", err)
	}

	// The skipped duplicate must not have changed the existing row (DO NOTHING, not DO UPDATE).
	items, err := repo.Select(ctx, "SELECT * FROM "+conflictScratchTable+" WHERE a = 'p' AND b = 'q'")
	if err != nil {
		t.Fatalf("Select: %v", err)
	}
	if len(items) != 1 {
		t.Fatalf("expected exactly 1 row for (a,b)=('p','q'), got %d", len(items))
	}
	if items[0].C != "v1" {
		t.Fatalf("expected the DO NOTHING duplicate to leave c untouched (still v1), got %q", items[0].C)
	}
}

// TestUpdateOrInsert verifies UpdateOrInsert's two paths against the same (a,b) business
// identity: the first call finds no matching row (ErrNoRows from the UPDATE) and falls back to
// the INSERT, which also carries its own ON CONFLICT clause; the second call finds the
// now-existing row and takes the UPDATE path instead, returning the same id and leaving no
// second row behind.
func TestUpdateOrInsert(t *testing.T) {
	db, err := openConflictTestConnection()
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	ctx := context.Background()
	if err = setupConflictScratchTable(ctx, db); err != nil {
		t.Fatal(err)
	}
	defer db.Exec(ctx, "DROP TABLE IF EXISTS "+conflictScratchTable)

	updateQuery := "UPDATE " + conflictScratchTable + " SET c = 'updated' WHERE a = $1 AND b = $2 RETURNING id"
	insertQuery := "INSERT INTO " + conflictScratchTable + " (a,b,c) VALUES ($1,$2,$3) " +
		"ON CONFLICT (a,b) DO UPDATE SET c = EXCLUDED.c RETURNING id"

	args := []any{"k1", "v1"}

	// Insert-fallback path: no row matches (a,b) yet.
	insertedID, err := UpdateOrInsert[int64](ctx, db, updateQuery, insertQuery, args, "fresh")
	if err != nil {
		t.Fatalf("UpdateOrInsert (insert-fallback path): %v", err)
	}
	if insertedID == 0 {
		t.Fatal("expected a non-zero id from the insert-fallback path")
	}

	repo := NewRepository[conflictScratchItem](db)
	afterInsert, err := repo.SelectByID(ctx, insertedID)
	if err != nil {
		t.Fatalf("SelectByID after insert-fallback: %v", err)
	}
	if afterInsert.C != "fresh" {
		t.Fatalf("expected c=%q to come from insertExtraArgs after the insert-fallback path, got %q", "fresh", afterInsert.C)
	}

	// Update-hit path: the row now exists, so the UPDATE should match and return the same id -
	// insertExtraArgs ("ignored") must not be used this time.
	updatedID, err := UpdateOrInsert[int64](ctx, db, updateQuery, insertQuery, args, "ignored")
	if err != nil {
		t.Fatalf("UpdateOrInsert (update-hit path): %v", err)
	}
	if updatedID != insertedID {
		t.Fatalf("expected the update-hit path to return the same id %d, got %d", insertedID, updatedID)
	}

	afterUpdate, err := repo.SelectByID(ctx, updatedID)
	if err != nil {
		t.Fatalf("SelectByID after update-hit: %v", err)
	}
	if afterUpdate.C != "updated" {
		t.Fatalf("expected c=%q from the UPDATE path, got %q (insertExtraArgs must not have been used)", "updated", afterUpdate.C)
	}

	count, err := repo.Count(ctx, "SELECT COUNT(*) FROM "+conflictScratchTable+" WHERE a = 'k1' AND b = 'v1'")
	if err != nil {
		t.Fatalf("Count: %v", err)
	}
	if count != 1 {
		t.Fatalf("expected exactly 1 row for (a,b)=('k1','v1') after both calls, got %d", count)
	}
}
