package pg

import (
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"strings"
	"testing"
	"time"

	"github.com/kataras/pg/desc"
)

// These tests require a live PostgreSQL server, see getTestConnString (db_example_test.go) and
// the PG_CONNSTRING environment variable. Run with, e.g.:
//
//	PG_CONNSTRING="..." go test -run 'TestRepositoryCopyFromRoundTrip|TestRepositoryCopyFromMixedDefaultColumnIncluded|TestRepositoryCopyFromRollback|TestRepositoryCopyFromGoSidePassword' -v .

// copyScratchItem is a scratch entity registered only for this file's plain (non-password)
// tests, so Repository.CopyFrom can be exercised against a real registered table with both an
// AutoGenerated-free UUID primary key default (gen_random_uuid()) and a timestamp default
// (clock_timestamp()): the two column categories BuildCopyPlan's all-zero omission rule exists
// for. Its scratch table is created/dropped with plain DDL (see setupCopyScratchTable below),
// mirroring paginationItem/setupPaginationScratchTable in pagination_live_test.go, rather than
// via DB.CreateSchema/DeleteSchema, which drops the whole search_path schema and would be
// unsafe to run against a database shared with other concurrently running tests/tasks.
type copyScratchItem struct {
	ID        string    `pg:"type=uuid,primary,default=gen_random_uuid()"`
	Name      string    `pg:"type=varchar(255)"`
	Score     int       `pg:"type=int"`
	CreatedAt time.Time `pg:"type=timestamp,default=clock_timestamp()"`
}

const copyScratchTable = "test_copy_scratch_items"

// openCopyTestConnection opens a *DB whose schema has only copyScratchItem registered, so
// Repository[copyScratchItem].CopyFrom can resolve its table descriptor.
func openCopyTestConnection() (*DB, error) {
	schema := NewSchema()
	schema.MustRegister(copyScratchTable, copyScratchItem{})

	return Open(context.Background(), schema, getTestConnString())
}

// setupCopyScratchTable (re)creates copyScratchTable with plain DDL, mirroring the scratch-table
// pattern already used by setupCRUDScratchTable (db_crud_live_test.go) and
// setupPaginationScratchTable (pagination_live_test.go). It also ensures the pgcrypto extension
// is installed, since gen_random_uuid() (the UUID primary key's DB-side default) depends on it;
// CREATE EXTENSION IF NOT EXISTS is idempotent and safe to run concurrently with any other test
// or task doing the same against this shared database.
func setupCopyScratchTable(ctx context.Context, db *DB) error {
	if _, err := db.Exec(ctx, "CREATE EXTENSION IF NOT EXISTS pgcrypto"); err != nil {
		return err
	}

	if _, err := db.Exec(ctx, "DROP TABLE IF EXISTS "+copyScratchTable); err != nil {
		return err
	}

	_, err := db.Exec(ctx, fmt.Sprintf(`CREATE TABLE %s (
		id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
		name VARCHAR(255) NOT NULL,
		score INT NOT NULL,
		created_at TIMESTAMP NOT NULL DEFAULT clock_timestamp()
	)`, copyScratchTable))
	return err
}

// TestRepositoryCopyFromRoundTrip verifies the 1000-row happy path end to end: CopyFrom reports
// exactly 1000 rows copied, every row's Name/Score round-trips through Select unchanged, and -
// because every row in this batch leaves ID and CreatedAt at their Go zero values -
// desc.BuildCopyPlan omits both Default-bearing columns from the COPY column list entirely. That
// omission is the thing under test: it must prove the DB-side defaults (gen_random_uuid(),
// clock_timestamp()) actually fired for the omitted columns, not merely that 1000 rows arrived,
// so every returned ID is asserted to be a well-formed, unique, non-zero UUID and every
// CreatedAt to be non-zero and to fall within this test's own execution window.
func TestRepositoryCopyFromRoundTrip(t *testing.T) {
	db, err := openCopyTestConnection()
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	ctx := context.Background()
	if err := setupCopyScratchTable(ctx, db); err != nil {
		t.Fatal(err)
	}
	defer dropTestTables(ctx, db, copyScratchTable)

	repo := NewRepository[copyScratchItem](db)

	const n = 1000
	testStart := time.Now().Add(-time.Minute) // generous clock-skew tolerance.

	values := make([]copyScratchItem, n)
	for i := range values {
		values[i] = copyScratchItem{
			Name:  fmt.Sprintf("item-%d", i),
			Score: i,
			// ID and CreatedAt are intentionally left zero on every row, so BuildCopyPlan must
			// omit both columns and let gen_random_uuid()/clock_timestamp() fire.
		}
	}

	copied, err := repo.CopyFrom(ctx, values)
	if err != nil {
		t.Fatalf("CopyFrom: %v", err)
	}
	if copied != n {
		t.Fatalf("CopyFrom returned %d, want %d", copied, n)
	}

	rows, err := repo.Select(ctx, fmt.Sprintf("SELECT * FROM %s ORDER BY score", copyScratchTable))
	if err != nil {
		t.Fatalf("Select: %v", err)
	}
	if len(rows) != n {
		t.Fatalf("Select returned %d rows, want %d", len(rows), n)
	}

	seenIDs := make(map[string]bool, n)
	for i, row := range rows {
		if row.Name != fmt.Sprintf("item-%d", i) || row.Score != i {
			t.Fatalf("row %d: unexpected Name/Score: %+v", i, row)
		}

		// gen_random_uuid() must have fired: a well-formed, non-zero UUID string.
		if len(row.ID) != 36 || row.ID == "00000000-0000-0000-0000-000000000000" {
			t.Fatalf("row %d: ID %q does not look like a gen_random_uuid() result", i, row.ID)
		}
		if seenIDs[row.ID] {
			t.Fatalf("row %d: duplicate ID %q (gen_random_uuid() should produce a unique value per row)", i, row.ID)
		}
		seenIDs[row.ID] = true

		// clock_timestamp() must have fired: non-zero and within this test's execution window.
		if row.CreatedAt.IsZero() {
			t.Fatalf("row %d: CreatedAt is zero, want the clock_timestamp() default to have fired", i)
		}
		if row.CreatedAt.Before(testStart) {
			t.Fatalf("row %d: CreatedAt %v predates the test's own start %v", i, row.CreatedAt, testStart)
		}
	}
}

// TestRepositoryCopyFromMixedDefaultColumnIncluded covers the other half of BuildCopyPlan's
// all-or-nothing decision that TestRepositoryCopyFromRoundTrip doesn't: a Default-bearing column
// (CreatedAt) that is INCLUDED because at least one row in the batch is non-zero for it. Per
// desc.BuildCopyPlan's documented divergence from InsertMany, every row's value for an included
// column (even a zero one) must be sent verbatim, never replaced by DEFAULT. This asserts both
// halves of that round trip through the real binary-COPY encode path (shared with the
// already-proven INSERT binding, so this is a cheap addition): the row with an explicit,
// in-the-past CreatedAt comes back with that exact value (not overwritten by clock_timestamp()),
// and the row that left CreatedAt zero comes back as the zero time.Time (not a freshly-fired
// default), proving the column was streamed as data, not treated as omitted.
func TestRepositoryCopyFromMixedDefaultColumnIncluded(t *testing.T) {
	db, err := openCopyTestConnection()
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	ctx := context.Background()
	if err := setupCopyScratchTable(ctx, db); err != nil {
		t.Fatal(err)
	}
	defer dropTestTables(ctx, db, copyScratchTable)

	repo := NewRepository[copyScratchItem](db)

	explicit := time.Date(2020, 6, 15, 12, 30, 0, 0, time.UTC)
	values := []copyScratchItem{
		{Name: "mixed-explicit", Score: 1, CreatedAt: explicit}, // non-zero: forces the column to be included.
		{Name: "mixed-zero", Score: 2},                          // CreatedAt left zero on purpose.
	}

	copied, err := repo.CopyFrom(ctx, values)
	if err != nil {
		t.Fatalf("CopyFrom: %v", err)
	}
	if copied != int64(len(values)) {
		t.Fatalf("CopyFrom returned %d, want %d", copied, len(values))
	}

	rows, err := repo.Select(ctx, fmt.Sprintf("SELECT * FROM %s ORDER BY score", copyScratchTable))
	if err != nil {
		t.Fatalf("Select: %v", err)
	}
	if len(rows) != len(values) {
		t.Fatalf("Select returned %d rows, want %d", len(rows), len(values))
	}

	if !rows[0].CreatedAt.Equal(explicit) {
		t.Fatalf("row %q: CreatedAt = %v, want the explicit value %v sent verbatim", rows[0].Name, rows[0].CreatedAt, explicit)
	}
	if !rows[1].CreatedAt.IsZero() {
		t.Fatalf("row %q: CreatedAt = %v, want the zero time.Time (COPY has no per-row DEFAULT; the column was included, so its zero row must be stored as zero, not clock_timestamp())", rows[1].Name, rows[1].CreatedAt)
	}
}

// errForcedCopyRollback is returned from inside TestRepositoryCopyFromRollback's InTransaction
// callback, after a successful CopyFrom, to force the surrounding transaction to roll back.
var errForcedCopyRollback = errors.New("forced rollback for CopyFrom rollback test")

// TestRepositoryCopyFromRollback verifies CopyFrom participates correctly in a surrounding
// transaction: run inside Repository.InTransaction, CopyFrom itself reports the rows as copied
// (COPY sees them within the still-open transaction), but once the callback returns a non-nil
// error the whole transaction rolls back and none of the copied rows are visible afterwards.
func TestRepositoryCopyFromRollback(t *testing.T) {
	db, err := openCopyTestConnection()
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	ctx := context.Background()
	if err := setupCopyScratchTable(ctx, db); err != nil {
		t.Fatal(err)
	}
	defer dropTestTables(ctx, db, copyScratchTable)

	repo := NewRepository[copyScratchItem](db)

	values := []copyScratchItem{
		{Name: "rollback-a", Score: 1},
		{Name: "rollback-b", Score: 2},
	}

	txErr := repo.InTransaction(ctx, func(txRepo *Repository[copyScratchItem]) error {
		copied, err := txRepo.CopyFrom(ctx, values)
		if err != nil {
			return err
		}
		if copied != int64(len(values)) {
			t.Fatalf("CopyFrom (inside transaction) returned %d, want %d", copied, len(values))
		}

		return errForcedCopyRollback
	})
	if !errors.Is(txErr, errForcedCopyRollback) {
		t.Fatalf("expected the forced rollback error to propagate out of InTransaction, got: %v", txErr)
	}

	count, err := repo.Count(ctx, fmt.Sprintf("SELECT COUNT(*) FROM %s", copyScratchTable))
	if err != nil {
		t.Fatalf("Count: %v", err)
	}
	if count != 0 {
		t.Fatalf("expected 0 rows after the rollback, got %d - CopyFrom did not roll back with the rest of the transaction", count)
	}
}

// copyPasswordScratchItem is a scratch entity for TestRepositoryCopyFromGoSidePassword: a
// password column that, once a Go-side desc.PasswordHandler is installed via
// Schema.HandlePassword, CopyFrom must encrypt per row instead of returning desc.ErrCopyPassword.
type copyPasswordScratchItem struct {
	ID       string `pg:"type=uuid,primary,default=gen_random_uuid()"`
	Username string `pg:"type=varchar(255),username"`
	Password string `pg:"type=varchar(255),password"`
}

const copyPasswordScratchTable = "test_copy_password_scratch_items"

// fakeCopyEncrypt/fakeCopyDecrypt form a trivial, reversible Go-side PasswordHandler pair for
// TestRepositoryCopyFromGoSidePassword, not real password hashing (this is a correctness test
// for CopyFrom's handler wiring, not for password security), but a byte-identical round trip is
// enough to prove Row actually calls the handler instead of falling back to the db-side
// crypt()/gen_salt() path or storing the plaintext.
func fakeCopyEncrypt(_, plainPassword string) (string, error) {
	return "enc:" + base64.StdEncoding.EncodeToString([]byte(plainPassword)), nil
}

func fakeCopyDecrypt(_, encryptedPassword string) (string, error) {
	raw, err := base64.StdEncoding.DecodeString(strings.TrimPrefix(encryptedPassword, "enc:"))
	if err != nil {
		return "", err
	}

	return string(raw), nil
}

// openCopyPasswordTestConnection opens a *DB whose schema has only copyPasswordScratchItem
// registered, with a Go-side PasswordHandler installed via Schema.HandlePassword.
func openCopyPasswordTestConnection() (*DB, error) {
	schema := NewSchema()
	schema.HandlePassword(desc.PasswordHandler{
		Encrypt: fakeCopyEncrypt,
		Decrypt: fakeCopyDecrypt,
	})
	schema.MustRegister(copyPasswordScratchTable, copyPasswordScratchItem{})

	return Open(context.Background(), schema, getTestConnString())
}

// setupCopyPasswordScratchTable (re)creates copyPasswordScratchTable with plain DDL, mirroring
// setupCopyScratchTable above.
func setupCopyPasswordScratchTable(ctx context.Context, db *DB) error {
	if _, err := db.Exec(ctx, "CREATE EXTENSION IF NOT EXISTS pgcrypto"); err != nil {
		return err
	}

	if _, err := db.Exec(ctx, "DROP TABLE IF EXISTS "+copyPasswordScratchTable); err != nil {
		return err
	}

	_, err := db.Exec(ctx, fmt.Sprintf(`CREATE TABLE %s (
		id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
		username VARCHAR(255) NOT NULL,
		password VARCHAR(255) NOT NULL
	)`, copyPasswordScratchTable))
	return err
}

// TestRepositoryCopyFromGoSidePassword verifies that, given a table with a Go-side
// desc.PasswordHandler (Schema.HandlePassword), CopyFrom encrypts each row's password in Go
// before streaming it to PostgreSQL, proven two ways: a raw, unmapped SELECT shows the stored
// value is not the plaintext (and matches fakeCopyEncrypt's own format), and Select's automatic
// per-row decrypt (desc/scanner.go's passwordTextScanner) hands the plaintext back unchanged.
func TestRepositoryCopyFromGoSidePassword(t *testing.T) {
	db, err := openCopyPasswordTestConnection()
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	ctx := context.Background()
	if err := setupCopyPasswordScratchTable(ctx, db); err != nil {
		t.Fatal(err)
	}
	defer dropTestTables(ctx, db, copyPasswordScratchTable)

	repo := NewRepository[copyPasswordScratchItem](db)

	values := []copyPasswordScratchItem{
		{Username: "alice", Password: "alice-secret"},
		{Username: "bob", Password: "bob-secret"},
	}

	copied, err := repo.CopyFrom(ctx, values)
	if err != nil {
		t.Fatalf("CopyFrom: %v", err)
	}
	if copied != int64(len(values)) {
		t.Fatalf("CopyFrom returned %d, want %d", copied, len(values))
	}

	var rawPassword string
	err = db.QueryRow(ctx,
		fmt.Sprintf("SELECT password FROM %s WHERE username = $1", copyPasswordScratchTable), "alice").
		Scan(&rawPassword)
	if err != nil {
		t.Fatalf("raw select: %v", err)
	}
	if rawPassword == "alice-secret" {
		t.Fatal("expected the stored password to be encrypted by the Go-side handler, got the plaintext")
	}
	if !strings.HasPrefix(rawPassword, "enc:") {
		t.Fatalf("stored password %q does not look like fakeCopyEncrypt's output - CopyFrom may not have called the handler", rawPassword)
	}

	rows, err := repo.Select(ctx, fmt.Sprintf("SELECT * FROM %s ORDER BY username", copyPasswordScratchTable))
	if err != nil {
		t.Fatalf("Select: %v", err)
	}
	if len(rows) != len(values) {
		t.Fatalf("Select returned %d rows, want %d", len(rows), len(values))
	}

	want := map[string]string{"alice": "alice-secret", "bob": "bob-secret"}
	for _, row := range rows {
		if row.Password != want[row.Username] {
			t.Fatalf("user %q: decrypted Password = %q, want %q", row.Username, row.Password, want[row.Username])
		}
	}
}
