package desc

// ColumnBasicInfo represents a basic column information, contains the table name, column name, ordinal position, column default value,
// data type, data type argument, whether the column is nullable, whether the column is identity and whether the column is generated.
type ColumnBasicInfo struct {
	TableName        string
	TableDescription string
	TableType        TableType
	Name             string
	OrdinalPosition  int
	Description      string
	Default          string
	DataType         DataType
	DataTypeArgument string
	IsNullable       bool
	IsIdentity       bool
	IsGenerated      bool
}

var _ ColumnBuilder = (*ColumnBasicInfo)(nil)

func (c *ColumnBasicInfo) BuildColumn(column *Column) error {
	column.TableName = c.TableName
	column.TableDescription = c.TableDescription
	column.TableType = c.TableType
	column.Name = c.Name
	column.Description = c.Description
	column.OrdinalPosition = c.OrdinalPosition
	column.Default = c.Default
	column.Type = c.DataType
	column.TypeArgument = c.DataTypeArgument
	column.Nullable = c.IsNullable
	// column.Required = !c.IsNullable
	column.Identity = c.IsIdentity
	column.AutoGenerated = c.IsGenerated

	column.FieldIndex = []int{c.OrdinalPosition}
	column.FieldName = ToStructFieldName(c.Name)
	column.FieldType = c.DataType.GoType()

	return nil
}
