package desc

import (
	"errors"
	"fmt"
	"reflect"
)

// ErrCopyPassword is returned by BuildCopyPlan when a table has a password column that
// PostgreSQL itself hashes on insert: via the crypt($N, gen_salt('<PasswordAlg>')) SQL
// fragment buildInsertPassword embeds into BuildInsertQuery/BuildBulkInsertQuery whenever
// Table.PasswordHandler has no Go-side Encrypt func. The COPY protocol streams raw column
// values straight into the table and cannot invoke a SQL function per row the way a regular
// INSERT can, so that db-side hashing path has no COPY equivalent at all.
//
// Callers that hit ErrCopyPassword have two ways out: fall back to Repository.InsertMany /
// DB.InsertSingle for this table (both still support the db-side crypt() path), or install a
// Go-side desc.PasswordHandler via Schema.HandlePassword so BuildCopyPlan can encrypt the
// password itself, in Go, before handing each row to COPY.
var ErrCopyPassword = errors.New("desc: table hashes its password column in the database via crypt()/gen_salt(); COPY cannot run SQL functions per row - use InsertMany, or install a Go-side PasswordHandler")

// CopyPlan holds the precomputed column list and per-row value extraction for a COPY FROM of a
// table's struct values, built once by BuildCopyPlan and then replayed for every row via Row.
//
// Unlike a single- or multi-row INSERT, a COPY statement has no per-row DEFAULT: a column is
// either present in every row of the stream or entirely absent from it, and PostgreSQL only
// applies a column's DB-side default to a column that is completely missing from the COPY
// column list, never to an individual row within an included column. See BuildCopyPlan's doc
// for exactly how CopyPlan resolves that per-column, all-or-nothing decision from per-row
// zero-value data, including its loudly documented divergence from InsertMany: a zero value in
// a column BuildCopyPlan decides to include is copied as that zero value, verbatim, never as
// DEFAULT.
type CopyPlan struct {
	// ColumnNames is the ordered list of columns the COPY statement will receive, the same
	// order Row returns its values in. It never includes an AutoGenerated or Presenter column
	// (mirroring Table.NumInsertableColumns/BuildBulkInsertQuery's column-selection predicate),
	// and it omits any Default-bearing column BuildCopyPlan determined was zero in every row of
	// the plan.
	ColumnNames []string

	cols []*Column // parallel to ColumnNames; kept for Row's field extraction.
	td   *Table    // needed by Row for password encryption (PasswordHandler.Encrypt(td.Name, ...)).
}

// wouldDefaultForRow reports whether field, the reflect.Value of one row's struct field for
// column c, is a value that BuildBulkInsertQuery would have replaced with the literal DEFAULT
// keyword for that row, had this been a regular multi-row INSERT instead of a COPY: either
// isZero(field) is true, or (mirroring writeBulkInsertHeaderAndValues's/extractArguments's own
// belt-and-suspenders second check) c is a non-nullable UUID primary key with a DB-side default
// whose interfaced value is zero. Both call sites, desc/insert_query.go's
// writeBulkInsertHeaderAndValues and desc/argument.go's extractArguments, run this same pair of
// checks per row; BuildCopyPlan's pre-pass below applies it across every row of a column instead
// of per row, since COPY cannot make the decision per row.
func wouldDefaultForRow(c *Column, field reflect.Value) bool {
	if isZero(field) {
		return true
	}

	if c.Type == UUID && !c.Nullable && c.PrimaryKey && field.CanInterface() && isZero(field.Interface()) {
		return true
	}

	return false
}

// BuildCopyPlan computes the COPY column list for the given rows of td and validates that the
// table's columns are representable under the COPY protocol, returning a *CopyPlan ready to
// extract each row's values via Row. structValues must be non-empty and every value must be a
// reflect.Value of (or addressable to) td's registered struct type, exactly as
// BuildBulkInsertQuery expects.
//
// Column selection proceeds in three steps:
//
//  1. Columns marked AutoGenerated or Presenter are skipped entirely: the exact predicate
//     Table.NumInsertableColumns encodes and BuildBulkInsertQuery's column loop uses, kept in
//     sync with both.
//
//  2. A password column requires a Go-side Table.PasswordHandler (installed via
//     Schema.HandlePassword) to be usable under COPY at all: see ErrCopyPassword's doc for why.
//     A password column with no working PasswordHandler makes BuildCopyPlan return
//     ErrCopyPassword immediately, before step 3 runs for any column.
//
//  3. Every remaining column with no Default is always included, verbatim, for every row. A
//     column that DOES carry a non-empty Default gets one reflection pre-pass over every row in
//     structValues, using wouldDefaultForRow: if every row's value for that column would have
//     triggered DEFAULT under BuildBulkInsertQuery, the column is omitted from ColumnNames
//     entirely, so PostgreSQL applies the column's own DB-side default (e.g. clock_timestamp(),
//     gen_random_uuid()) to every row of the COPY. COPY only ever applies a default to a column
//     that is completely absent from its column list. If even a single row's value is non-zero,
//     the column is included instead, and Row sends EVERY row's value for it verbatim,
//     including the zero-valued rows.
//
// Unlike BuildBulkInsertQuery (which can never drop a column, since a zero-valued row just swaps
// in a literal DEFAULT token instead of omitting the column), step 3 above CAN end up omitting
// every remaining column, if every one of them carries a Default and is zero across the whole
// batch. BuildCopyPlan detects that case and returns a descriptive error rather than building a
// CopyPlan with an empty ColumnNames, which would otherwise reach PostgreSQL as a COPY statement
// with an empty column list and fail with a raw syntax error instead.
//
// That last point is the sharpest divergence from InsertMany/BuildBulkInsertQuery, which decide
// DEFAULT-vs-value independently for each row: under COPY there is no per-row DEFAULT keyword, so
// a "mostly defaulted, occasionally set" column is only representable by including the column and
// sending its zero value literally for the rows that would otherwise have been defaulted. A zero
// value in an included column is therefore stored as the literal zero (e.g. an all-zeros UUID, or
// the timestamp's zero time.Time), never as DEFAULT. A caller that needs the DB default to fire
// for individual zero-valued rows of a column that is not all-zero across the whole batch must
// use InsertMany for that load instead of CopyFrom.
func BuildCopyPlan(td *Table, structValues []reflect.Value) (*CopyPlan, error) {
	if len(structValues) == 0 {
		return nil, fmt.Errorf("desc: BuildCopyPlan: no values to copy")
	}

	// Step 1: AutoGenerated/Presenter columns never participate in COPY, same as INSERT.
	candidates := make([]*Column, 0, len(td.Columns))
	for _, c := range td.Columns {
		if c.AutoGenerated || c.Presenter {
			continue
		}

		candidates = append(candidates, c)
	}
	if len(candidates) == 0 {
		return nil, fmt.Errorf(`desc: BuildCopyPlan: no columns to copy, maybe missing struct field tag of "%s"`, DefaultTag)
	}

	// Step 2: a db-side-hashed password column has no COPY equivalent at all.
	for _, c := range candidates {
		if c.Password && !td.PasswordHandler.canEncrypt() {
			return nil, ErrCopyPassword
		}
	}

	// Step 3: resolve the all-or-nothing DEFAULT decision for every Default-bearing column.
	cols := make([]*Column, 0, len(candidates))
	for _, c := range candidates {
		if c.Default == "" {
			cols = append(cols, c)
			continue
		}

		allDefault := true
		for _, sv := range structValues {
			field := sv.FieldByIndex(c.FieldIndex)
			if !field.CanInterface() {
				// Unreadable field: treat it as if it were zero, mirroring
				// writeBulkInsertHeaderAndValues's own "unreadable field -> DEFAULT" fallback
				// for this same obscure struct-layout-quirk case.
				continue
			}

			if !wouldDefaultForRow(c, field) {
				allDefault = false
				break
			}
		}

		if allDefault {
			continue // every row is zero for this column: omit it so the DB default fires.
		}

		cols = append(cols, c)
	}

	// cols can come out empty here even though candidates was not (see BuildCopyPlan's doc,
	// above): guard against handing pgx an empty column list, which would otherwise reach
	// PostgreSQL as `copy "schema"."table" (  ) from stdin binary;` and fail with a raw syntax
	// error instead of this descriptive one.
	if len(cols) == 0 {
		return nil, fmt.Errorf("desc: BuildCopyPlan: every insertable column of %q was omitted because it is zero in every row and carries a database default; set at least one value in the batch, or use InsertMany, which can emit a per-row DEFAULT instead of requiring an all-or-nothing column decision", td.Name)
	}

	names := make([]string, len(cols))
	for i, c := range cols {
		names[i] = c.Name
	}

	return &CopyPlan{
		ColumnNames: names,
		cols:        cols,
		td:          td,
	}, nil
}

// Row extracts (and, for a Go-side password handler, encrypts) the COPY values of one struct
// value, in ColumnNames order, ready to hand straight to pgx.CopyFromSlice/pgx.CopyFromFunc as
// that row's []any.
//
// A password column reaching Row is necessarily backed by a working Table.PasswordHandler (see
// BuildCopyPlan, which returns ErrCopyPassword before Row is ever called for a table that lacks
// one): Row encrypts it here, per row, exactly like the single- and multi-row INSERT paths do -
// the field must be a non-empty string, or Row returns an error naming the offending column,
// matching extractArguments's (desc/argument.go) and writeBulkInsertHeaderAndValues's
// (desc/insert_query.go) own password validation error text.
func (p *CopyPlan) Row(structValue reflect.Value) ([]any, error) {
	values := make([]any, len(p.cols))

	for i, c := range p.cols {
		field := structValue.FieldByIndex(c.FieldIndex)
		if !field.CanInterface() {
			// Unreadable field: there is no per-row DEFAULT to fall back to under COPY (see
			// BuildCopyPlan's doc), so send NULL and let PostgreSQL enforce NOT NULL/its own
			// default itself if that turns out to be wrong for this column.
			values[i] = nil
			continue
		}

		fieldValue := field.Interface()

		if c.Password {
			pwStr, ok := fieldValue.(string)
			if !ok {
				return nil, fmt.Errorf("password field: %s is not string", c.Name)
			}
			if pwStr == "" {
				return nil, fmt.Errorf("password field: %s is empty", c.Name)
			}

			enc, err := p.td.PasswordHandler.Encrypt(p.td.Name, pwStr)
			if err != nil {
				return nil, fmt.Errorf("password handler: set: %w", err)
			}

			fieldValue = enc
		}

		values[i] = fieldValue
	}

	return values, nil
}
