package desc

import (
	"errors"
	"fmt"
	"reflect"
	"strings"
	"testing"
	"time"
)

// copyPlanRow is the representative struct for BuildCopyPlan/CopyPlan.Row's unit tests: a UUID
// primary key with an implicit DB-side default (see ConvertStructToTable's auto-default rule for
// a non-nullable UUID primary key with no explicit default tag), a plain no-default column, a
// Default-bearing non-PK column, and one Presenter and one AutoGenerated column that must never
// reach a COPY statement.
type copyPlanRow struct {
	ID        string    `pg:"type=uuid,primary"`
	Email     string    `pg:"type=varchar(255)"`
	CreatedAt time.Time `pg:"type=timestamp,default=clock_timestamp()"`
	Computed  string    `pg:"type=varchar(255),presenter"`
	Search    string    `pg:"type=varchar(255),auto"`
}

// copyPlanRowTable builds the *Table for copyPlanRow via ConvertStructToTable, the same path
// production code uses, so these tests exercise the real column resolution (including the
// auto-default UUID primary key rule) too.
func copyPlanRowTable(t *testing.T) *Table {
	t.Helper()

	td, err := ConvertStructToTable("copy_plan_rows", reflect.TypeFor[copyPlanRow]())
	if err != nil {
		t.Fatalf("ConvertStructToTable: %v", err)
	}

	return td
}

// TestBuildCopyPlanColumnSelection exercises the column-selection rules documented on
// BuildCopyPlan: a no-default column is always included, a Default-bearing column is omitted
// only when it is zero in EVERY row of the plan, and Presenter/AutoGenerated columns never
// appear in ColumnNames regardless of their values.
func TestBuildCopyPlanColumnSelection(t *testing.T) {
	td := copyPlanRowTable(t)

	t.Run("all-zero default columns omitted, no-default column always included, presenter/auto-generated skipped", func(t *testing.T) {
		values := []reflect.Value{
			reflect.ValueOf(copyPlanRow{Email: "a@example.com"}),
			reflect.ValueOf(copyPlanRow{Email: "b@example.com"}),
		}

		plan, err := BuildCopyPlan(td, values)
		if err != nil {
			t.Fatalf("BuildCopyPlan: %v", err)
		}

		want := []string{"email"}
		if !reflect.DeepEqual(plan.ColumnNames, want) {
			t.Fatalf("ColumnNames = %v, want %v (id/created_at are zero in every row and must be omitted so their DB defaults fire; computed/search are presenter/auto-generated and must never appear)", plan.ColumnNames, want)
		}
	})

	t.Run("no-default column is included even when zero in every row", func(t *testing.T) {
		// Email carries no Default tag, so (unlike id/created_at above) it must never be
		// subject to the all-zero omission rule: it stays in ColumnNames even though it is the
		// empty string ("", its zero value) in every row of this plan.
		values := []reflect.Value{
			reflect.ValueOf(copyPlanRow{}),
			reflect.ValueOf(copyPlanRow{}),
		}

		plan, err := BuildCopyPlan(td, values)
		if err != nil {
			t.Fatalf("BuildCopyPlan: %v", err)
		}

		want := []string{"email"}
		if !reflect.DeepEqual(plan.ColumnNames, want) {
			t.Fatalf("ColumnNames = %v, want %v (email has no Default and must be included regardless of being zero in every row)", plan.ColumnNames, want)
		}
	})

	t.Run("mixed default column is included and sent verbatim, including its zero rows", func(t *testing.T) {
		values := []reflect.Value{
			reflect.ValueOf(copyPlanRow{Email: "a@example.com"}),                             // CreatedAt zero.
			reflect.ValueOf(copyPlanRow{Email: "b@example.com", CreatedAt: time.Unix(1, 0)}), // CreatedAt non-zero.
		}

		plan, err := BuildCopyPlan(td, values)
		if err != nil {
			t.Fatalf("BuildCopyPlan: %v", err)
		}

		want := []string{"email", "created_at"}
		if !reflect.DeepEqual(plan.ColumnNames, want) {
			t.Fatalf("ColumnNames = %v, want %v (created_at has a non-zero row, so the whole column must be included)", plan.ColumnNames, want)
		}

		row0, err := plan.Row(values[0])
		if err != nil {
			t.Fatalf("Row(0): %v", err)
		}
		got, ok := row0[1].(time.Time)
		if !ok || !got.IsZero() {
			t.Fatalf("Row(0)[created_at] = %#v, want the zero time.Time sent verbatim (COPY has no per-row DEFAULT, unlike InsertMany)", row0[1])
		}
	})
}

// TestBuildCopyPlanNoValuesErrors verifies BuildCopyPlan rejects an empty structValues slice
// instead of silently building a plan around a nonexistent all-zero pre-pass.
func TestBuildCopyPlanNoValuesErrors(t *testing.T) {
	td := copyPlanRowTable(t)

	if _, err := BuildCopyPlan(td, nil); err == nil {
		t.Fatal("expected an error for an empty structValues slice, got nil")
	}
}

// copyPlanAllDefaultRow's only insertable columns (id, created_at; both Presenter/AutoGenerated
// columns are absent here on purpose) carry a Default. Unlike copyPlanRow, which always has a
// no-default column (Email) to fall back on, a batch of copyPlanAllDefaultRow values left at
// their Go zero values gives BuildCopyPlan's step-3 pre-pass nothing to include: every candidate
// column is omitted, which is exactly the "no columns left to copy" shape
// TestBuildCopyPlanAllColumnsOmittedErrors exercises.
type copyPlanAllDefaultRow struct {
	ID        string    `pg:"type=uuid,primary"`
	CreatedAt time.Time `pg:"type=timestamp,default=clock_timestamp()"`
}

// TestBuildCopyPlanAllColumnsOmittedErrors verifies BuildCopyPlan returns a descriptive error
// (instead of a *CopyPlan with an empty ColumnNames, which pgx would turn into a COPY statement
// with an empty column list and PostgreSQL would then reject with a raw syntax error) when every
// one of a table's insertable columns carries a Default and is zero across the whole batch, so
// the step-3 pre-pass omits all of them.
func TestBuildCopyPlanAllColumnsOmittedErrors(t *testing.T) {
	td, err := ConvertStructToTable("copy_plan_all_default_rows", reflect.TypeFor[copyPlanAllDefaultRow]())
	if err != nil {
		t.Fatalf("ConvertStructToTable: %v", err)
	}

	values := []reflect.Value{
		reflect.ValueOf(copyPlanAllDefaultRow{}),
		reflect.ValueOf(copyPlanAllDefaultRow{}),
	}

	plan, err := BuildCopyPlan(td, values)
	if err == nil {
		t.Fatalf("expected an error when every insertable column is omitted, got a plan with ColumnNames = %v", plan.ColumnNames)
	}
	if !strings.Contains(err.Error(), "InsertMany") {
		t.Fatalf("expected the error to point callers at InsertMany as the alternative, got: %v", err)
	}
}

// copyPlanPasswordRow has a password column. TestBuildCopyPlanDBSidePasswordRejected leaves its
// table's PasswordHandler nil (the db-side crypt() path); TestCopyPlanRowGoSideHandlerEncrypts
// installs a fake Go-side one.
type copyPlanPasswordRow struct {
	Email    string `pg:"type=varchar(255)"`
	Password string `pg:"type=varchar(255),password"`
}

// TestBuildCopyPlanDBSidePasswordRejected verifies BuildCopyPlan returns ErrCopyPassword, not a
// plan that would silently stream the plaintext password to PostgreSQL, for a table whose
// password column has no Go-side PasswordHandler installed.
func TestBuildCopyPlanDBSidePasswordRejected(t *testing.T) {
	td, err := ConvertStructToTable("copy_plan_password_rows", reflect.TypeFor[copyPlanPasswordRow]())
	if err != nil {
		t.Fatalf("ConvertStructToTable: %v", err)
	}
	// td.PasswordHandler is intentionally left nil: the db-side crypt()/gen_salt() path.

	values := []reflect.Value{reflect.ValueOf(copyPlanPasswordRow{Email: "a@example.com", Password: "secret"})}

	if _, err := BuildCopyPlan(td, values); !errors.Is(err, ErrCopyPassword) {
		t.Fatalf("expected ErrCopyPassword, got: %v", err)
	}
}

// TestCopyPlanRowOrderMatchesColumnNames verifies Row returns its values in exactly the order
// ColumnNames lists them.
func TestCopyPlanRowOrderMatchesColumnNames(t *testing.T) {
	td := copyPlanRowTable(t)

	when := time.Date(2024, 1, 2, 3, 4, 5, 0, time.UTC)
	values := []reflect.Value{
		reflect.ValueOf(copyPlanRow{ID: "11111111-1111-1111-1111-111111111111", Email: "a@example.com", CreatedAt: when}),
	}

	plan, err := BuildCopyPlan(td, values)
	if err != nil {
		t.Fatalf("BuildCopyPlan: %v", err)
	}

	wantNames := []string{"id", "email", "created_at"}
	if !reflect.DeepEqual(plan.ColumnNames, wantNames) {
		t.Fatalf("ColumnNames = %v, want %v", plan.ColumnNames, wantNames)
	}

	row, err := plan.Row(values[0])
	if err != nil {
		t.Fatalf("Row: %v", err)
	}
	if len(row) != len(plan.ColumnNames) {
		t.Fatalf("Row returned %d values, want %d (one per ColumnNames entry)", len(row), len(plan.ColumnNames))
	}

	wantRow := []any{"11111111-1111-1111-1111-111111111111", "a@example.com", when}
	if !reflect.DeepEqual(row, wantRow) {
		t.Fatalf("Row = %#v, want %#v (same order as ColumnNames: id,email,created_at)", row, wantRow)
	}
}

// TestCopyPlanRowGoSideHandlerEncrypts verifies that, once a table carries a Go-side
// desc.PasswordHandler, BuildCopyPlan includes the password column (instead of returning
// ErrCopyPassword) and Row calls the handler's Encrypt func once per row (storing its return
// value, never the plaintext, as that row's password value) and that an empty password still
// errors out of Row, matching the single-/multi-row INSERT paths' own validation.
func TestCopyPlanRowGoSideHandlerEncrypts(t *testing.T) {
	td, err := ConvertStructToTable("copy_plan_handler_password_rows", reflect.TypeFor[copyPlanPasswordRow]())
	if err != nil {
		t.Fatalf("ConvertStructToTable: %v", err)
	}

	var encryptCalls []string
	td.PasswordHandler = &PasswordHandler{
		Encrypt: func(tableName, plainPassword string) (string, error) {
			encryptCalls = append(encryptCalls, plainPassword)
			return fmt.Sprintf("enc(%s:%s)", tableName, plainPassword), nil
		},
	}

	values := []reflect.Value{
		reflect.ValueOf(copyPlanPasswordRow{Email: "a@example.com", Password: "secret-a"}),
		reflect.ValueOf(copyPlanPasswordRow{Email: "b@example.com", Password: "secret-b"}),
	}

	plan, err := BuildCopyPlan(td, values)
	if err != nil {
		t.Fatalf("BuildCopyPlan: %v", err)
	}

	wantNames := []string{"email", "password"}
	if !reflect.DeepEqual(plan.ColumnNames, wantNames) {
		t.Fatalf("ColumnNames = %v, want %v", plan.ColumnNames, wantNames)
	}

	row0, err := plan.Row(values[0])
	if err != nil {
		t.Fatalf("Row(0): %v", err)
	}
	if row0[1] != "enc(copy_plan_handler_password_rows:secret-a)" {
		t.Fatalf("Row(0)[password] = %v, want the handler's encrypted return value, not the plaintext", row0[1])
	}

	row1, err := plan.Row(values[1])
	if err != nil {
		t.Fatalf("Row(1): %v", err)
	}
	if row1[1] != "enc(copy_plan_handler_password_rows:secret-b)" {
		t.Fatalf("Row(1)[password] = %v, want the handler's encrypted return value", row1[1])
	}

	wantCalls := []string{"secret-a", "secret-b"}
	if !reflect.DeepEqual(encryptCalls, wantCalls) {
		t.Fatalf("Encrypt calls = %v, want %v (called exactly once per row, in row order)", encryptCalls, wantCalls)
	}

	t.Run("empty password errors", func(t *testing.T) {
		emptyValues := []reflect.Value{reflect.ValueOf(copyPlanPasswordRow{Email: "c@example.com", Password: ""})}
		emptyPlan, err := BuildCopyPlan(td, emptyValues)
		if err != nil {
			t.Fatalf("BuildCopyPlan: %v", err)
		}

		if _, err := emptyPlan.Row(emptyValues[0]); err == nil {
			t.Fatal("expected an error for an empty password field, got nil")
		}
	})
}
