package desc

import (
	"fmt"
	"reflect"
	"strconv"
	"strings"
)

// DefaultInsertBatchSize is the default maximum number of rows per
// bulk-insert statement. Kept well below Postgres's 65535 bind-param
// ceiling so even wide structs (dozens of columns) fit without
// splitting mid-statement. Callers with unusually wide rows should
// pick a smaller size to stay under 65535 / columns.
const DefaultInsertBatchSize = 500

// BuildInsertQuery builds and returns an SQL query for inserting a row into the table,
// based on the given struct value, arguments, and returning column.
// The struct value is a reflect.Value of the struct that represents the row to be inserted.
// The arguments are a slice of Argument that contains the column definitions and values for each field of the struct.
// The returning column is an optional string that specifies which column to return after the insertion,
// such as the primary key or any other generated value.
func BuildInsertQuery(td *Table, structValue reflect.Value, idPtr any, forceOnConflictExpr string, upsert bool) (string, []any, error) {
	returningColumn := "" // a variable to store the name of the column to return after insertion
	if idPtr != nil {
		// if idPtr is not nil, it means we want to get the primary key value of the inserted row
		columnDefinition, ok := td.PrimaryKey() // get the primary key column definition from the table definition
		if ok {
			returningColumn = columnDefinition.Name // assign the column name to returningColumn
		}
	}

	// find the arguments for the SQL query based on the struct value and the table definition
	args, err := extractArguments(td, structValue, nil)
	if err != nil {
		return "", nil, err // return the error if finding arguments fails
	}

	if len(args) == 0 {
		return "", nil, fmt.Errorf(`no arguments found, maybe missing struct field tag of "%s"`, DefaultTag) // return an error if no arguments are found.
	}

	// build the SQL query using the table definition,
	// the arguments and the returning column
	query, err := buildInsertQuery(td, args, returningColumn, forceOnConflictExpr, upsert)
	if err != nil {
		return "", nil, err
	}

	return query, args.Values(), nil
}

// BuildBulkInsertQuery builds a single multi-row INSERT statement for
// the given struct values. All values must be of the same type as td.
//
// Semantics mirror BuildInsertQuery for every individual row:
//   - Columns marked AutoGenerated or Presenter are never written.
//   - A zero-valued field whose column carries a DB default is emitted
//     as the literal DEFAULT keyword (not a parameter) so the default
//     fires (e.g. clock_timestamp() for audit columns, gen_random_uuid()
//     for UUID primary keys).
//   - Password columns are handled identically to the single-row path.
//
// The column set is the union of columns any row would write — the
// header is computed once from td, and per-row the value is either a
// $N placeholder or DEFAULT. This keeps the header stable across rows
// while still honoring per-row "skip zero" semantics.
//
// Pair with DB.InsertMany / Repository.InsertMany which batch this at
// DefaultInsertBatchSize to stay under Postgres's 65535 bind-param cap.
func BuildBulkInsertQuery(td *Table, structValues []reflect.Value, forceOnConflictExpr string, upsert bool) (string, []any, error) {
	if len(structValues) == 0 {
		return "", nil, fmt.Errorf("no values to insert")
	}

	// Collect the column set: every non-AutoGenerated, non-Presenter column
	// in declaration order. Passwords are kept — they get special handling
	// per-row below.
	cols := make([]*Column, 0, len(td.Columns))
	for _, c := range td.Columns {
		if c.AutoGenerated || c.Presenter {
			continue
		}
		cols = append(cols, c)
	}
	if len(cols) == 0 {
		return "", nil, fmt.Errorf(`no columns to insert, maybe missing struct field tag of "%s"`, DefaultTag)
	}

	// Determine conflicts for the ON CONFLICT clause — identical logic
	// to the single-row path.
	var conflicts []string
	onConflictExpression, hasConflict := td.OnConflict()
	for _, c := range cols {
		if hasConflict {
			if c.Unique {
				conflicts = append(conflicts, c.Name)
			}
		} else if c.UniqueIndex != "" {
			conflicts = append(conflicts, c.Name)
		}
	}

	if forceOnConflictExpr != "" {
		uniqueIndexes := td.UniqueIndexes()
		if sel, ok := uniqueIndexes[forceOnConflictExpr]; ok {
			conflicts = sel
		} else {
			for _, cn := range conflicts {
				if cn == forceOnConflictExpr {
					conflicts = []string{forceOnConflictExpr}
				}
			}
		}
		if len(conflicts) == 0 {
			return "", nil, fmt.Errorf("can't find unique index with name: %s", forceOnConflictExpr)
		}
		onConflictExpression = buildDoUpdateFromExcluded(cols, conflicts)
	} else if upsert && len(conflicts) > 0 && !hasConflict {
		onConflictExpression = buildDoUpdateFromExcluded(cols, conflicts)
	} else {
		conflicts = nil
	}

	var b strings.Builder
	b.WriteString(`INSERT INTO`)
	b.WriteByte(' ')
	writeTableName(&b, td.SearchPath, td.Name)
	b.WriteByte(' ')

	// (col1,col2,...)
	b.WriteByte(leftParenLiteral)
	for i, c := range cols {
		if i > 0 {
			b.WriteByte(',')
		}
		b.WriteString(c.Name)
	}
	b.WriteByte(rightParenLiteral)

	// VALUES (...),(...),...
	b.WriteByte(' ')
	b.WriteString(`VALUES`)
	b.WriteByte(' ')

	args := make([]any, 0, len(structValues)*len(cols))
	paramIndex := 0
	for rowIdx, sv := range structValues {
		if rowIdx > 0 {
			b.WriteByte(',')
		}
		b.WriteByte(leftParenLiteral)
		for i, c := range cols {
			if i > 0 {
				b.WriteByte(',')
			}

			field := sv.FieldByIndex(c.FieldIndex)
			if !field.CanInterface() {
				// Treat unreadable field as DEFAULT so we don't blow up the
				// whole batch for one obscure struct layout quirk.
				b.WriteString("DEFAULT")
				continue
			}
			fieldValue := field.Interface()

			// Mirror extractArguments's "skip zero when default is set" rule:
			// emit DEFAULT instead of a param so the DB-side default fires.
			if c.Default != "" && isZero(field) {
				b.WriteString("DEFAULT")
				continue
			}
			if c.Default != "" && c.Type == UUID && !c.Nullable && c.PrimaryKey && isZero(fieldValue) {
				b.WriteString("DEFAULT")
				continue
			}

			// Password column encryption — same as single-row path.
			if c.Password {
				if td.PasswordHandler.canEncrypt() {
					pwStr, ok := fieldValue.(string)
					if !ok {
						return "", nil, fmt.Errorf("password field: %s is not string", c.Name)
					}
					if pwStr == "" {
						return "", nil, fmt.Errorf("password field: %s is empty", c.Name)
					}
					enc, err := td.PasswordHandler.Encrypt(td.Name, pwStr)
					if err != nil {
						return "", nil, fmt.Errorf("password handler: set: %w", err)
					}
					fieldValue = enc
					paramIndex++
					b.WriteByte('$')
					b.WriteString(strconv.Itoa(paramIndex))
				} else {
					paramIndex++
					b.WriteString(buildInsertPassword("$" + strconv.Itoa(paramIndex)))
				}
				args = append(args, fieldValue)
				continue
			}

			paramIndex++
			b.WriteByte('$')
			b.WriteString(strconv.Itoa(paramIndex))
			args = append(args, fieldValue)
		}
		b.WriteByte(rightParenLiteral)
	}

	if len(conflicts) > 0 {
		b.WriteByte(' ')
		b.WriteString(`ON CONFLICT`)
		b.WriteByte(leftParenLiteral)
		b.WriteString(strings.Join(conflicts, ","))
		b.WriteByte(rightParenLiteral)
		b.WriteByte(' ')
		b.WriteString(onConflictExpression)
	}

	b.WriteByte(';')
	return b.String(), args, nil
}

// buildDoUpdateFromExcluded emits "DO UPDATE SET col = EXCLUDED.col, ..."
// for every column not in the conflict set — the same form the single-row
// builder uses for full upserts.
func buildDoUpdateFromExcluded(cols []*Column, conflicts []string) string {
	var b strings.Builder
	b.WriteString(`DO UPDATE SET `)
	j := 0
	for _, c := range cols {
		excluded := false
		for _, cn := range conflicts {
			if cn == c.Name {
				excluded = true
				break
			}
		}
		if excluded {
			continue
		}
		if j > 0 {
			b.WriteByte(',')
		}
		fmt.Fprintf(&b, "%s = EXCLUDED.%s", c.Name, c.Name)
		j++
	}
	return b.String()
}

func buildInsertQuery(td *Table, args Arguments, returningColumn string, forceOnConflictExpr string, upsert bool) (string, error) {
	var b strings.Builder

	// INSERT INTO "schema"."tableName"
	b.WriteString(`INSERT INTO`)
	b.WriteByte(' ')
	writeTableName(&b, td.SearchPath, td.Name)
	b.WriteByte(' ')

	var (
		namedParametersValues = make([]string, 0, len(td.Columns))
		columnNamesToInsert   = make([]string, 0, len(td.Columns))
		paramIndex            int

		conflicts []string
	)

	// (record_id,record)
	b.WriteByte(leftParenLiteral)

	onConflictExpression, hasConflict := td.OnConflict()

	i := 0
	for _, a := range args {
		c := a.Column

		if i > 0 {
			b.WriteByte(',')
		}

		if hasConflict {
			// if conflict is empty then an error of: duplicate key value violates unique constraint "$key"
			// will be fired, otherwise even if one is exists
			// then error will be ignored but we can't use the returning id.

			if c.Unique {
				conflicts = append(conflicts, c.Name)
			}
		} else if c.UniqueIndex != "" {
			conflicts = append(conflicts, c.Name)
		}

		paramIndex++ // starts from 1.
		paramIndexStr := strconv.Itoa(paramIndex)
		paramName := "$" + paramIndexStr

		if c.Password {
			if td.PasswordHandler.canEncrypt() {
				// handled at args state.
			} else {
				paramName = buildInsertPassword(paramName)
			}
		}

		namedParametersValues = append(namedParametersValues, paramName)
		columnNamesToInsert = append(columnNamesToInsert, c.Name)

		b.WriteString(c.Name)
		i++
	}

	if len(namedParametersValues) == 0 {
		return "", fmt.Errorf("no columns to insert")
	}

	// set on conflict expression by custom unqiue index or column name
	// even if upsert is not true.
	if forceOnConflictExpr != "" {
		uniqueIndexes := td.UniqueIndexes()

		selectedUniqueIndexColumns, ok := uniqueIndexes[forceOnConflictExpr]
		if ok {
			conflicts = selectedUniqueIndexColumns // override the conflicts.
		} else {
			// if not found then check for unique index OR unique by column name.
			for _, conflict := range conflicts {
				if conflict == forceOnConflictExpr {
					conflicts = []string{forceOnConflictExpr} // override the conflicts.
				}
			}
		}

		if len(conflicts) == 0 { // force check of conflicts.
			return "", fmt.Errorf("can't find unique index with name: %s", forceOnConflictExpr)
		}

		// override the on conflict expression.
		onConflictExpression = `DO UPDATE SET `
		j := 0
		for _, colName := range columnNamesToInsert {
			excluded := false
			for _, conflict := range conflicts { // skip the conflict columns.
				if conflict == colName {
					excluded = true
				}
			}

			if excluded {
				continue
			}
			if j > 0 {
				onConflictExpression += ","
			}

			onConflictExpression += fmt.Sprintf(`%s = EXCLUDED.%s`, colName, colName)
			j++
		}
	} else if upsert && len(conflicts) > 0 && !hasConflict {
		// if asked for upsert and forceOnConflictExpr is empty, conflicts are set from unique_index or unique as always,
		// but on conflict tag was not set manually then generate a full upsert method to update all columns.

		// override the on conflict expression.
		onConflictExpression = `DO UPDATE SET `
		j := 0
		for _, colName := range columnNamesToInsert {
			excluded := false
			for _, conflict := range conflicts { // skip the conflict columns.
				if conflict == colName {
					excluded = true
				}
			}

			if excluded {
				continue
			}
			if j > 0 {
				onConflictExpression += ","
			}

			onConflictExpression += fmt.Sprintf(`%s = EXCLUDED.%s`, colName, colName)
			j++
		}
	} else {
		// If had unique tags but no custom on conflict expression then ignore them,
		// so the caller receives a duplication error.
		conflicts = nil
	}

	b.WriteByte(rightParenLiteral)

	// VALUES($1,$2,$3)
	b.WriteByte(' ')
	b.WriteString(`VALUES`)

	b.WriteByte(leftParenLiteral)
	b.WriteString(strings.Join(namedParametersValues, ","))
	b.WriteByte(rightParenLiteral)

	if len(conflicts) > 0 {
		// ON CONFLICT(record_id)
		b.WriteByte(' ')
		b.WriteString(`ON CONFLICT`)

		b.WriteByte(leftParenLiteral)
		b.WriteString(strings.Join(conflicts, ","))
		b.WriteByte(rightParenLiteral)

		b.WriteByte(' ')
		b.WriteString(onConflictExpression)

		if returningColumn != "" && strings.Contains(strings.ToUpper(onConflictExpression), "DO UPDATE") {
			// we can still use the returning column (source: https://stackoverflow.com/a/37543015).
			writeInsertReturning(&b, returningColumn)
		}
	} else if returningColumn != "" {
		writeInsertReturning(&b, returningColumn)
	}

	b.WriteByte(';')

	query := b.String()
	return query, nil
}

func writeTableName(b *strings.Builder, schema, tableName string) {
	b.WriteString(strconv.Quote(schema))
	b.WriteByte('.')
	b.WriteString(strconv.Quote(tableName))
}

// PasswordAlg is the password algorithm the library uses to tell postgres
// how to generate a password field's salt.
// Alternatives:
// md5
// xdes
// des
var PasswordAlg = "bf" // max password length: 72, salt bits: 128, output length: 60, blowfish-based.

const (
	singleQuoteLiteral = '\''
)

// crypt($1,gen_salt('PasswordAlg'))
func buildInsertPassword(paramName string) string {
	var b strings.Builder

	// crypt($1,
	b.WriteString(`crypt`)
	b.WriteByte(leftParenLiteral)
	b.WriteString(paramName)

	b.WriteByte(',')

	// gen_salt('bf')
	b.WriteString(`gen_salt`)
	b.WriteByte(leftParenLiteral)
	b.WriteByte(singleQuoteLiteral)
	b.WriteString(PasswordAlg)
	b.WriteByte(singleQuoteLiteral)
	b.WriteByte(rightParenLiteral)

	// )
	b.WriteByte(rightParenLiteral)
	return b.String()
}

func writeInsertReturning(b *strings.Builder, columnKey string) {
	if columnKey == "" {
		return
	}

	b.WriteByte(' ')
	b.WriteString(`RETURNING`)
	b.WriteByte(' ')
	b.WriteString(columnKey)
}
