package desc

import (
	"fmt"
	"reflect"
	"slices"
	"strconv"
	"strings"

	"github.com/jackc/pgx/v5"
)

// DefaultInsertBatchSize is the default maximum number of rows per
// bulk-insert statement. Kept well below Postgres's 65535 bind-param
// ceiling so even wide structs (dozens of columns) fit without
// splitting mid-statement. Callers with unusually wide rows should
// pick a smaller size to stay under 65535 / columns.
const DefaultInsertBatchSize = 500

// BuildInsertQuery builds and returns an SQL query for inserting a row into the table,
// based on the given struct value, arguments, and returning column.
// The struct value is a reflect.Value of the struct that represents the row to be inserted.
// The arguments are a slice of Argument that contains the column definitions and values for each field of the struct.
// The returning column is an optional string that specifies which column to return after the insertion,
// such as the primary key or any other generated value.
func BuildInsertQuery(td *Table, structValue reflect.Value, idPtr any, forceOnConflictExpr string, upsert bool) (string, []any, error) {
	returningColumn := "" // a variable to store the name of the column to return after insertion
	if idPtr != nil {
		// if idPtr is not nil, it means we want to get the primary key value of the inserted row
		columnDefinition, ok := td.PrimaryKey() // get the primary key column definition from the table definition
		if ok {
			returningColumn = columnDefinition.Name // assign the column name to returningColumn
		}
	}

	// find the arguments for the SQL query based on the struct value and the table definition
	args, err := extractArguments(td, structValue, nil)
	if err != nil {
		return "", nil, err // return the error if finding arguments fails
	}

	if len(args) == 0 {
		return "", nil, fmt.Errorf(`no arguments found, maybe missing struct field tag of "%s"`, DefaultTag) // return an error if no arguments are found.
	}

	// build the SQL query using the table definition,
	// the arguments and the returning column
	query, err := buildInsertQuery(td, args, returningColumn, forceOnConflictExpr, upsert)
	if err != nil {
		return "", nil, err
	}

	return query, args.Values(), nil
}

// BuildBulkInsertQuery builds a single multi-row INSERT statement for
// the given struct values. All values must be of the same type as td.
//
// Semantics mirror BuildInsertQuery for every individual row:
//   - Columns marked AutoGenerated or Presenter are never written.
//   - A zero-valued field whose column carries a DB default is emitted
//     as the literal DEFAULT keyword (not a parameter) so the default
//     fires (e.g. clock_timestamp() for audit columns, gen_random_uuid()
//     for UUID primary keys).
//   - Password columns are handled identically to the single-row path.
//
// The column set is the union of columns any row would write. The
// header is computed once from td, and per-row the value is either a
// $N placeholder or DEFAULT. This keeps the header stable across rows
// while still honoring per-row "skip zero" semantics.
//
// Pair with DB.InsertMany / Repository.InsertMany which batch this at
// DefaultInsertBatchSize to stay under Postgres's 65535 bind-param cap.
func BuildBulkInsertQuery(td *Table, structValues []reflect.Value, forceOnConflictExpr string, upsert bool) (string, []any, error) {
	if len(structValues) == 0 {
		return "", nil, fmt.Errorf("no values to insert")
	}

	// Collect the column set: every non-AutoGenerated, non-Presenter column
	// in declaration order. Passwords are kept: they get special handling
	// per-row below.
	cols := make([]*Column, 0, len(td.Columns))
	for _, c := range td.Columns {
		if c.AutoGenerated || c.Presenter {
			continue
		}
		cols = append(cols, c)
	}
	if len(cols) == 0 {
		return "", nil, fmt.Errorf(`no columns to insert, maybe missing struct field tag of "%s"`, DefaultTag)
	}

	// Determine conflicts for the ON CONFLICT clause: identical logic
	// to the single-row path (see tagConflictTarget).
	conflicts, hasTarget, onConflictExpression, err := tagConflictTarget(td, cols, forceOnConflictExpr, upsert)
	if err != nil {
		return "", nil, err
	}

	var b strings.Builder
	b.WriteString(`INSERT INTO`)
	b.WriteByte(' ')
	writeTableName(&b, td.SearchPath, td.Name)
	b.WriteByte(' ')

	args, err := writeBulkInsertHeaderAndValues(&b, td, cols, structValues)
	if err != nil {
		return "", nil, err
	}

	writeOnConflictClause(&b, hasTarget, conflictTargetSQL(conflicts), onConflictExpression, "", false)

	b.WriteByte(';')
	return b.String(), args, nil
}

// writeBulkInsertHeaderAndValues writes "(col1,col2,...) VALUES (row1),(row2),..." for a bulk
// insert. It is the column list and per-row placeholder/DEFAULT emission shared by
// BuildBulkInsertQuery and BuildBulkInsertQueryOnConflict (on_conflict.go), and returns the
// bind arguments in emission order. cols is the full ordered set of columns every row writes
// (AutoGenerated/Presenter already excluded by the caller).
func writeBulkInsertHeaderAndValues(b *strings.Builder, td *Table, cols []*Column, structValues []reflect.Value) ([]any, error) {
	// (col1,col2,...)
	b.WriteByte(leftParenLiteral)
	for i, c := range cols {
		if i > 0 {
			b.WriteByte(',')
		}
		b.WriteString(c.Name)
	}
	b.WriteByte(rightParenLiteral)

	// VALUES (...),(...),...
	b.WriteByte(' ')
	b.WriteString(`VALUES`)
	b.WriteByte(' ')

	args := make([]any, 0, len(structValues)*len(cols))
	paramIndex := 0
	for rowIdx, sv := range structValues {
		if rowIdx > 0 {
			b.WriteByte(',')
		}
		b.WriteByte(leftParenLiteral)
		for i, c := range cols {
			if i > 0 {
				b.WriteByte(',')
			}

			field := sv.FieldByIndex(c.FieldIndex)
			if !field.CanInterface() {
				// Treat unreadable field as DEFAULT so we don't blow up the
				// whole batch for one obscure struct layout quirk.
				b.WriteString("DEFAULT")
				continue
			}
			fieldValue := field.Interface()

			// Mirror extractArguments's "skip zero when default is set" rule:
			// emit DEFAULT instead of a param so the DB-side default fires.
			if c.Default != "" && isZero(field) {
				b.WriteString("DEFAULT")
				continue
			}
			if c.Default != "" && c.Type == UUID && !c.Nullable && c.PrimaryKey && isZero(fieldValue) {
				b.WriteString("DEFAULT")
				continue
			}

			// Password column encryption: same as single-row path.
			if c.Password {
				if td.PasswordHandler.canEncrypt() {
					pwStr, ok := fieldValue.(string)
					if !ok {
						return nil, fmt.Errorf("password field: %s is not string", c.Name)
					}
					if pwStr == "" {
						return nil, fmt.Errorf("password field: %s is empty", c.Name)
					}
					enc, err := td.PasswordHandler.Encrypt(td.Name, pwStr)
					if err != nil {
						return nil, fmt.Errorf("password handler: set: %w", err)
					}
					fieldValue = enc
					paramIndex++
					b.WriteByte('$')
					b.WriteString(strconv.Itoa(paramIndex))
				} else {
					if err := validatePasswordAlg(); err != nil {
						return nil, err
					}

					paramIndex++
					b.WriteString(buildInsertPassword("$" + strconv.Itoa(paramIndex)))
				}
				args = append(args, fieldValue)
				continue
			}

			paramIndex++
			b.WriteByte('$')
			b.WriteString(strconv.Itoa(paramIndex))
			args = append(args, fieldValue)
		}
		b.WriteByte(rightParenLiteral)
	}

	return args, nil
}

// writeOnConflictClause writes the " ON CONFLICT<targetSQL> <action>" fragment, and, per
// buildInsertQuery's long-standing RETURNING rule, an appended " RETURNING <returningColumn>".
// Both are shared by all four insert builders (BuildInsertQuery, BuildBulkInsertQuery,
// BuildInsertQueryOnConflict, BuildBulkInsertQueryOnConflict in on_conflict.go), so they all emit
// this fragment identically.
//
// targetSQL is written immediately after the ON CONFLICT keyword with no inserted space, so
// callers supply their own leading space when needed: "(col1,col2)" for a column-list target,
// " ON CONSTRAINT name" for a named-constraint target.
//
// RETURNING is appended when returningColumn is non-empty, and either hasTarget is false (no
// conflict target at all: a plain insert with RETURNING) or alwaysReturning is true, or action
// contains "DO UPDATE". The DO-UPDATE-only condition is what the tag-driven builders have always
// used (a DO NOTHING silently drops the conflicting row, so unconditional RETURNING would report
// no rows in a way indistinguishable from a query error: see
// https://stackoverflow.com/a/37543015); the explicit-OnConflict builders instead pass
// alwaysReturning=true, since InsertSingleOnConflict wants a DO-NOTHING-skipped row to reliably
// surface as ErrNoRows via the RETURNING clause returning zero rows.
func writeOnConflictClause(b *strings.Builder, hasTarget bool, targetSQL, action, returningColumn string, alwaysReturning bool) {
	if hasTarget {
		b.WriteByte(' ')
		b.WriteString(`ON CONFLICT`)
		b.WriteString(targetSQL)
		b.WriteByte(' ')
		b.WriteString(action)

		if returningColumn != "" && (alwaysReturning || strings.Contains(strings.ToUpper(action), "DO UPDATE")) {
			// we can still use the returning column (source: https://stackoverflow.com/a/37543015).
			writeInsertReturning(b, returningColumn)
		}
	} else if returningColumn != "" {
		writeInsertReturning(b, returningColumn)
	}
}

// doNothingExpr is the literal ON CONFLICT action tagConflictTarget recognizes as "do nothing on
// conflict", matching the root package's exported `pg.DoNothing` constant value byte-for-byte (the
// desc package cannot import the root package to reference it directly: that would be an import
// cycle, since the root package imports desc). It is also the value BuildInsertQuery/
// BuildBulkInsertQuery honor when it appears as a `conflict` struct tag (Column.Conflict, surfaced
// via Table.OnConflict), e.g. `pg:"unique,conflict=DO NOTHING"`.
const doNothingExpr = "DO NOTHING"

// isDoNothingExpr reports whether expr is (case-insensitively, surrounding whitespace ignored) the
// literal doNothingExpr action, as opposed to a unique index name (a forceOnConflictExpr value) or
// a raw SQL DO UPDATE fragment (a Column.Conflict tag value other than "DO NOTHING").
func isDoNothingExpr(expr string) bool {
	return strings.EqualFold(strings.TrimSpace(expr), doNothingExpr)
}

// conflictTargetSQL renders the "(col1,col2)" ON CONFLICT target-column-list fragment for
// writeOnConflictClause's targetSQL parameter, or "" when conflicts is empty. The empty case
// matters for a target-less "ON CONFLICT DO NOTHING" (valid Postgres; "ON CONFLICT()" is not).
func conflictTargetSQL(conflicts []string) string {
	if len(conflicts) == 0 {
		return ""
	}
	return "(" + strings.Join(conflicts, ",") + ")"
}

// tagConflictTarget computes the tag-driven ON CONFLICT target and DO UPDATE/DO NOTHING action
// exactly as BuildInsertQuery/BuildBulkInsertQuery have always derived them from struct tags
// (Column.Unique, Column.UniqueIndex, Column.Conflict) and the forceOnConflictExpr/upsert
// parameters:
//
//   - forceOnConflictExpr equal (case-insensitively) to doNothingExpr ("DO NOTHING", the same
//     value as the root package's pg.DoNothing constant) forces a DO NOTHING action targeting
//     whatever tag-derived conflict columns cols carries, which may be none, in which case
//     hasTarget is still true and the caller emits a target-less "ON CONFLICT DO NOTHING" (valid
//     Postgres: it fires on a conflict against any unique constraint on the table). This never
//     errors merely because "DO NOTHING" is not a named unique index.
//   - otherwise, forceOnConflictExpr, when set, selects a named unique index (or a specific
//     conflicting column) and forces a full "col = EXCLUDED.col" DO UPDATE over every column in
//     cols outside that target;
//   - otherwise, when upsert is true and the table's `conflict` tag (Column.Conflict, surfaced via
//     Table.OnConflict) is itself doNothingExpr, the tag-derived Unique-column target (if any) is
//     used for a DO NOTHING action: the `conflict=DO NOTHING` struct-tag form;
//   - otherwise, when upsert is true and cols carry a tag-derived target but the table has no
//     `conflict` tag, a full DO UPDATE is generated automatically;
//   - otherwise any tag-derived target is discarded (conflicts is nil, hasTarget is false, and the
//     tag-derived onConflictExpression, a raw `conflict` tag value other than "DO NOTHING", is
//     never written) so a duplicate raises the database's own unique-violation error. This last,
//     dead-code case is unchanged from before: only the doNothingExpr tag value is now honored.
//
// cols is the full ordered set of columns this INSERT would write; conflicts/hasTarget/
// onConflictExpression are meant to be passed straight to writeOnConflictClause (conflicts via
// conflictTargetSQL for the targetSQL argument).
func tagConflictTarget(td *Table, cols []*Column, forceOnConflictExpr string, upsert bool) (conflicts []string, hasTarget bool, onConflictExpression string, err error) {
	onConflictExpression, hasConflict := td.OnConflict()

	for _, c := range cols {
		if hasConflict {
			if c.Unique {
				conflicts = append(conflicts, c.Name)
			}
		} else if c.UniqueIndex != "" {
			conflicts = append(conflicts, c.Name)
		}
	}

	names := make([]string, len(cols))
	for i, c := range cols {
		names[i] = c.Name
	}

	switch {
	case forceOnConflictExpr != "" && isDoNothingExpr(forceOnConflictExpr):
		onConflictExpression = doNothingExpr
		hasTarget = true
	case forceOnConflictExpr != "":
		uniqueIndexes := td.UniqueIndexes()
		if sel, ok := uniqueIndexes[forceOnConflictExpr]; ok {
			conflicts = sel
		} else {
			for _, cn := range conflicts {
				if cn == forceOnConflictExpr {
					conflicts = []string{forceOnConflictExpr}
				}
			}
		}
		if len(conflicts) == 0 {
			return nil, false, "", fmt.Errorf("can't find unique index with name: %s", forceOnConflictExpr)
		}
		onConflictExpression = buildDoUpdateFromExcludedNames(names, conflicts)
		hasTarget = true
	case upsert && hasConflict && isDoNothingExpr(onConflictExpression):
		onConflictExpression = doNothingExpr
		hasTarget = true
	case upsert && len(conflicts) > 0 && !hasConflict:
		onConflictExpression = buildDoUpdateFromExcludedNames(names, conflicts)
		hasTarget = true
	default:
		conflicts = nil
	}

	return conflicts, hasTarget, onConflictExpression, nil
}

// writeDoUpdateSetList writes "DO UPDATE SET <id> = EXCLUDED.<id>, ..." for each given
// identifier, in order, with no filtering. It is the tail shared by buildDoUpdateFromExcludedNames
// (which filters the conflict-target columns out first) and buildDoUpdateFromExcludedSubset
// (whose caller has already decided the final, exact identifier list).
func writeDoUpdateSetList(b *strings.Builder, identifiers []string) {
	b.WriteString(`DO UPDATE SET `)
	for i, id := range identifiers {
		if i > 0 {
			b.WriteByte(',')
		}
		fmt.Fprintf(b, "%s = EXCLUDED.%s", id, id)
	}
}

// buildDoUpdateFromExcludedNames emits "DO UPDATE SET col = EXCLUDED.col, ..." for every name in
// names that is not in conflicts, in the order given. It is the name-based core shared by
// buildDoUpdateFromExcluded (bulk builder, operates on *Column) and tagConflictTarget (single-row
// builder, operates on the column names already extracted for its args).
func buildDoUpdateFromExcludedNames(names, conflicts []string) string {
	filtered := make([]string, 0, len(names))
	for _, name := range names {
		if slices.Contains(conflicts, name) {
			continue
		}
		filtered = append(filtered, name)
	}

	var b strings.Builder
	writeDoUpdateSetList(&b, filtered)
	return b.String()
}

// buildDoUpdateFromExcludedSubset emits "DO UPDATE SET <id> = EXCLUDED.<id>, ..." for exactly the
// given identifiers (already quoted, or not, as the caller wants them to appear in the generated
// SQL). This is the OnConflict.SetColumns partial-update case (on_conflict.go's resolveOnConflict),
// and its empty-SetColumns fallback once the caller has already filtered the conflict target out of
// the identifier list. Unlike buildDoUpdateFromExcludedNames (which does
// their own conflict-target filtering against a set of bare column names), this performs no
// filtering: the caller decides exactly which identifiers appear, and in what form.
func buildDoUpdateFromExcludedSubset(identifiers []string) string {
	var b strings.Builder
	writeDoUpdateSetList(&b, identifiers)
	return b.String()
}

func buildInsertQuery(td *Table, args Arguments, returningColumn string, forceOnConflictExpr string, upsert bool) (string, error) {
	var b strings.Builder

	// INSERT INTO "schema"."tableName"
	b.WriteString(`INSERT INTO`)
	b.WriteByte(' ')
	writeTableName(&b, td.SearchPath, td.Name)
	b.WriteByte(' ')

	// (record_id,record)
	namedParametersValues, insertCols, err := writeInsertColumnList(&b, td, args)
	if err != nil {
		return "", err
	}

	if len(namedParametersValues) == 0 {
		return "", fmt.Errorf("no columns to insert")
	}

	// VALUES($1,$2,$3)
	b.WriteByte(' ')
	b.WriteString(`VALUES`)

	b.WriteByte(leftParenLiteral)
	b.WriteString(strings.Join(namedParametersValues, ","))
	b.WriteByte(rightParenLiteral)

	// set on conflict expression by custom unqiue index or column name
	// even if upsert is not true.
	conflicts, hasTarget, onConflictExpression, err := tagConflictTarget(td, insertCols, forceOnConflictExpr, upsert)
	if err != nil {
		return "", err
	}

	// A DO NOTHING action normally never appends RETURNING (see writeOnConflictClause's doc
	// comment): a skipped conflicting row would otherwise come back indistinguishable from a
	// query error. But for this single-row builder that has a sharp edge when the caller also
	// wants idPtr populated (returningColumn != ""): with no RETURNING clause at all, a
	// genuinely successful, non-conflicting insert would ALSO return zero rows, so the caller
	// could never tell "conflict, row skipped" apart from "inserted successfully". Every call
	// would look like a skip. So a DO NOTHING action here always gets RETURNING
	// (alwaysReturning=true) instead: a successful insert populates idPtr, and a skipped
	// conflicting row surfaces unambiguously as pgx.ErrNoRows. This is the same contract
	// BuildInsertQueryOnConflict already uses for OnConflict{DoNothing: true} (see its doc
	// comment and TestBuildInsertQueryOnConflictGolden's "do nothing always returns RETURNING
	// when idPtr is set"), so this aligns the legacy tag-driven path with an already-tested
	// semantic. BuildBulkInsertQuery is unaffected: it never passes a returningColumn at all.
	alwaysReturning := hasTarget && isDoNothingExpr(onConflictExpression)

	// ON CONFLICT(record_id) ...
	writeOnConflictClause(&b, hasTarget, conflictTargetSQL(conflicts), onConflictExpression, returningColumn, alwaysReturning)

	b.WriteByte(';')

	query := b.String()
	return query, nil
}

// writeInsertColumnList writes "(col1,col2,...)" for a single-row INSERT's column list, the
// opening and closing parens included. Shared by buildInsertQuery and BuildInsertQueryOnConflict
// (on_conflict.go).
//
// It returns, in the same order as args: the $N (or crypt(...)-wrapped $N for a
// PasswordHandler-less password column) placeholder for each column, ready to join into the
// VALUES(...) list, and the Column each placeholder came from, for ON CONFLICT target/action
// derivation.
func writeInsertColumnList(b *strings.Builder, td *Table, args Arguments) (namedParametersValues []string, cols []*Column, err error) {
	namedParametersValues = make([]string, 0, len(args))
	cols = make([]*Column, 0, len(args))
	paramIndex := 0

	b.WriteByte(leftParenLiteral)

	i := 0
	for _, a := range args {
		c := a.Column

		if i > 0 {
			b.WriteByte(',')
		}

		paramIndex++ // starts from 1.
		paramIndexStr := strconv.Itoa(paramIndex)
		paramName := "$" + paramIndexStr

		if c.Password {
			if td.PasswordHandler.canEncrypt() {
				// handled at args state.
			} else {
				if err := validatePasswordAlg(); err != nil {
					return nil, nil, err
				}

				paramName = buildInsertPassword(paramName)
			}
		}

		namedParametersValues = append(namedParametersValues, paramName)
		cols = append(cols, c)

		b.WriteString(c.Name)
		i++
	}

	b.WriteByte(rightParenLiteral)

	return namedParametersValues, cols, nil
}

// writeTableName writes the schema-qualified, SQL-identifier-quoted table name (e.g.
// "public"."users") to b. It uses pgx.Identifier.Sanitize, which double-quotes each part and
// doubles any embedded '"', the correct escaping for a Postgres identifier, rather than Go
// string quoting (strconv.Quote), which escapes '"' as '\"' (invalid inside a Postgres identifier)
// and mangles non-ASCII bytes into \uXXXX escapes.
func writeTableName(b *strings.Builder, schema, tableName string) {
	b.WriteString(pgx.Identifier{schema, tableName}.Sanitize())
}

// PasswordAlg is the password algorithm the library uses to tell postgres how to generate a
// password field's salt, via pgcrypto's gen_salt('<PasswordAlg>'), embedded verbatim into the
// crypt($N, gen_salt('<PasswordAlg>')) SQL fragment built by buildInsertPassword whenever a
// password column is inserted/updated without a PasswordHandler (i.e. postgres, not this
// library, does the hashing).
//
// Allowed values: "bf" (default, blowfish-based), "md5", "xdes", "des". Every query that would
// embed PasswordAlg calls validatePasswordAlg first and fails with an error for any other value,
// including one crafted to break out of the surrounding SQL string literal, instead of
// interpolating it.
//
// PasswordAlg must be set once, during program initialization (e.g. in an init func, or before
// the first query touching a password column is built), and never mutated concurrently with
// query building: it's a package-level variable read without synchronization by every insert/
// update that has a password column.
var PasswordAlg = "bf" // max password length: 72, salt bits: 128, output length: 60, blowfish-based.

// passwordAlgAllowlist is the set of gen_salt() algorithm identifiers pgcrypto accepts.
// validatePasswordAlg rejects any PasswordAlg value outside this set.
var passwordAlgAllowlist = map[string]bool{
	"bf":   true,
	"md5":  true,
	"xdes": true,
	"des":  true,
}

// validatePasswordAlg reports an error if PasswordAlg is not one of the allowlisted gen_salt()
// algorithm identifiers ("bf", "md5", "xdes", "des"). Every code path that builds SQL embedding
// PasswordAlg (see buildInsertPassword's callers) must call this first and propagate a non-nil
// result instead of building the query, since PasswordAlg is interpolated directly into a SQL
// string literal and an unvalidated value, e.g. containing a "'", could break out of it.
func validatePasswordAlg() error {
	if !passwordAlgAllowlist[PasswordAlg] {
		return fmt.Errorf("pg: invalid PasswordAlg %q: must be one of \"bf\", \"md5\", \"xdes\", \"des\"", PasswordAlg)
	}

	return nil
}

const (
	singleQuoteLiteral = '\''
)

// crypt($1,gen_salt('PasswordAlg'))
func buildInsertPassword(paramName string) string {
	var b strings.Builder

	// crypt($1,
	b.WriteString(`crypt`)
	b.WriteByte(leftParenLiteral)
	b.WriteString(paramName)

	b.WriteByte(',')

	// gen_salt('bf')
	b.WriteString(`gen_salt`)
	b.WriteByte(leftParenLiteral)
	b.WriteByte(singleQuoteLiteral)
	b.WriteString(PasswordAlg)
	b.WriteByte(singleQuoteLiteral)
	b.WriteByte(rightParenLiteral)

	// )
	b.WriteByte(rightParenLiteral)
	return b.String()
}

func writeInsertReturning(b *strings.Builder, columnKey string) {
	if columnKey == "" {
		return
	}

	b.WriteByte(' ')
	b.WriteString(`RETURNING`)
	b.WriteByte(' ')
	b.WriteString(columnKey)
}
