package desc

import "testing"

func TestColumnFieldTagString(t *testing.T) {
	c := &Column{
		Name:         "test",
		Type:         CharacterVarying,
		TypeArgument: "255",
		PrimaryKey:   true,
		Identity:     true,
		// Required:            true,
		Default:             "test_default",
		Unique:              true,
		Conflict:            "test_conflict",
		Username:            true,
		Password:            true,
		ReferenceTableName:  "test_reference_table_name",
		ReferenceColumnName: "test_reference_column_name",
		ReferenceOnDelete:   "test_reference_on_delete",
		DeferrableReference: true,
		Index:               Hash,
		UniqueIndex:         "test_unique_index",
		CheckConstraint:     "test_check_constraint",
		AutoGenerated:       true,
		Presenter:           true,
		Unscannable:         true,
	}

	expected := `pg:"name=test,type=varchar(255),primary,identity,default=test_default,unique,conflict=test_conflict,username,password,ref=test_reference_table_name(test_reference_column_name test_reference_on_delete deferrable),index=hash,unique_index=test_unique_index,check=test_check_constraint,auto,presenter,unscannable"`
	if got := c.FieldTagString(true); expected != got {
		t.Fatalf("expected field tag:\n%s\nbut got:\n%s", expected, got)
	}
}
